import { z } from 'zod';

const jobCreateValidationSchema = z.object({
  body: z.object({
    title: z.string().min(3, 'Title must be at least 3 characters').max(100),

    company: z.string().min(2, 'Company name is too short'),

    location: z.string().min(2, 'Location is too short'),

    category: z.string(),

    description: z.string().min(10, 'Description should be more detailed'),

    // Note: We omit id and createdAt because they are
    // auto-generated by PostgreSQL/Prisma.
  }),
});

// TypeScript type inference
export type TJobValidation = z.infer<typeof jobCreateValidationSchema>['body'];

export const JobValidation = {
  jobCreateValidationSchema,
};
